# Generated by Django 4.2.7 on 2026-05-26 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mockrecord",
            old_name="project_score",
            new_name="aptitude_score",
        ),
        migrations.RenameField(
            model_name="mockrecord",
            old_name="java_score",
            new_name="django_score",
        ),
        migrations.RenameField(
            model_name="mockrecord",
            old_name="communication_score",
            new_name="frontend_score",
        ),
    ]
