# Generated by Django 4.2.7 on 2026-05-26 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("company_name", models.CharField(max_length=200)),
                (
                    "company_code",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                ("description", models.TextField()),
                ("tech_stacks", models.CharField(max_length=200)),
                ("salary_package", models.CharField(max_length=100)),
                ("is_open_to_all", models.BooleanField(default=False)),
                ("deadline", models.DateTimeField()),
                (
                    "accept_mode",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manually Accept Applications"),
                            (
                                "AUTOMATIC",
                                "Automatically Shortlist Last-Moment Applications",
                            ),
                        ],
                        default="MANUAL",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "posted_by",
                    models.ForeignKey(
                        limit_choices_to={"role": "BD"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posted_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_batches",
                    models.ManyToManyField(related_name="jobs", to="accounts.batch"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPLIED", "Applied"),
                            ("SHORTLISTED", "Shortlisted"),
                            ("ROUND_2", "Cleared Round 2"),
                            ("FINAL_ROUND", "Cleared Final Round"),
                            ("SELECTED", "Selected"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="APPLIED",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("bd_feedback", models.TextField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="bd.job",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "job")},
            },
        ),
        migrations.CreateModel(
            name="BDMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                (
                    "file_attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="bd_attachments/"
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("BD_TO_STUDENT", "BD to Student"),
                            ("STUDENT_TO_BD", "Student to BD"),
                        ],
                        default="BD_TO_STUDENT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bd",
                    models.ForeignKey(
                        limit_choices_to={"role": "BD"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bd_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_bd_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApplicationTimeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stage", models.CharField(max_length=50)),
                ("comments", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline",
                        to="bd.jobapplication",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
